import { useEffect,useState } from 'react';
import { View,Text,TextInput,Pressable,FlatList,StyleSheet,Alert,Modal } from 'react-native';
import { supabase } from '../src/supabase';
import { Order } from '../src/types';
import { router } from 'expo-router';

const foods=[['1','Chicken Meal',120,'🍗'],['2','Burger & Fries',150,'🍔'],['3','Pancit Canton',100,'🍜'],['4','Pizza',220,'🍕'],['5','Milk Tea',90,'🧋'],['6','Lechon Meal',180,'🍖']];

export default function Customer(){
 const [orders,setOrders]=useState<Order[]>([]),[cart,setCart]=useState<any[]>([]),[address,setAddress]=useState(''),[chat,setChat]=useState(false),[msg,setMsg]=useState(''),[messages,setMessages]=useState<any[]>([]);
 async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {data}=await supabase.from('orders').select('*').eq('customer_id',u.user.id).order('created_at',{ascending:false});setOrders((data||[]) as Order[]);}
 function add(f:any){setCart(c=>{let x=c.find((a:any)=>a.id===f[0]);return x?c.map((a:any)=>a.id===f[0]?{...a,qty:a.qty+1}:a):[...c,{id:f[0],name:f[1],price:f[2],emoji:f[3],qty:1}]})}
 async function place(){if(!cart.length)return Alert.alert('Cart empty');if(!address.trim())return Alert.alert('Address required');const {data:u}=await supabase.auth.getUser();if(!u.user)return;const total=cart.reduce((s,x)=>s+x.price*x.qty,0);const items=cart.map(x=>`${x.name} x${x.qty}`).join(', ');const {error}=await supabase.from('orders').insert({customer_id:u.user.id,restaurant_name:'Tubigon Express',items,total,delivery_address:address,status:'pending'});if(error)Alert.alert('Error',error.message);else{setCart([]);setAddress('');load();Alert.alert('Order placed','A rider will receive your request.');}}
 async function openChat(){setChat(true);const {data:u}=await supabase.auth.getUser();if(u.user){const {data}=await supabase.from('support_messages').select('*').eq('customer_id',u.user.id).order('created_at');setMessages(data||[]);}}
 async function send(){if(!msg.trim())return;const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {error}=await supabase.from('support_messages').insert({customer_id:u.user.id,sender_role:'customer',message:msg.trim()});if(!error){setMsg('');openChat()}}
 useEffect(()=>{load();const ch=supabase.channel('customer-live').on('postgres_changes',{event:'*',schema:'public',table:'orders'},()=>load()).on('postgres_changes',{event:'*',schema:'public',table:'support_messages'},()=>openChat()).subscribe();return()=>{supabase.removeChannel(ch)}},[]);
 async function logout(){await supabase.auth.signOut();router.replace('/')}
 const total=cart.reduce((s,x)=>s+x.price*x.qty,0);
 return <View style={s.page}><View style={s.row}><Text style={s.h1}>Tubigon Express</Text><Pressable onPress={logout}><Text style={s.link}>Logout</Text></Pressable></View>
 <Text style={s.sub}>Order food directly. No store account required.</Text>
 <Text style={s.h2}>Choose your food</Text><FlatList data={foods} numColumns={2} keyExtractor={x=>x[0]} renderItem={({item})=><View style={s.food}><Text style={s.emoji}>{item[3]}</Text><Text style={s.bold}>{item[1]}</Text><Text>₱{item[2]}</Text><Pressable style={s.small} onPress={()=>add(item)}><Text style={s.bt}>Add</Text></Pressable></View>}/>
 {cart.length>0&&<View style={s.checkout}><Text style={s.bold}>{cart.length} item(s) • ₱{total}</Text><TextInput style={s.input} placeholder="Delivery address" value={address} onChangeText={setAddress}/><Pressable style={s.button} onPress={place}><Text style={s.bt}>Place Order</Text></Pressable></View>}
 <Text style={s.h2}>Live orders</Text><FlatList style={{maxHeight:170}} data={orders} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><Text style={s.bold}>#{item.id.slice(0,8)} • ₱{item.total}</Text><Text>{item.items}</Text><Text style={s.status}>{item.status.replace('_',' ').toUpperCase()}</Text></View>}/>
 <Pressable style={s.support} onPress={openChat}><Text style={s.bt}>💬 Chat Support</Text></Pressable>
 <Modal visible={chat} animationType="slide"><View style={s.modal}><View style={s.row}><Text style={s.h1}>Chat Support</Text><Pressable onPress={()=>setChat(false)}><Text style={s.link}>Close</Text></Pressable></View><FlatList style={{flex:1}} data={messages} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.message}><Text style={s.bold}>{item.sender_role==='customer'?'You':'Tubigon Express Support'}</Text><Text>{item.message}</Text></View>}/><View style={s.row}><TextInput style={[s.input,{flex:1}]} placeholder="Type a message..." value={msg} onChangeText={setMsg}/><Pressable style={s.small} onPress={send}><Text style={s.bt}>Send</Text></Pressable></View></View></Modal>
 </View>
}
const s=StyleSheet.create({page:{flex:1,padding:18,paddingTop:55,backgroundColor:'#f7f8fa'},modal:{flex:1,padding:18,paddingTop:55,backgroundColor:'#f7f8fa'},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},h1:{fontSize:25,fontWeight:'800'},sub:{color:'#68737d',marginVertical:5},h2:{fontSize:18,fontWeight:'800',marginTop:14,marginBottom:8},food:{backgroundColor:'#fff',margin:5,padding:12,borderRadius:14,flex:1},emoji:{fontSize:32},bold:{fontWeight:'800'},small:{backgroundColor:'#e53935',padding:9,borderRadius:9,alignItems:'center',marginTop:7},button:{backgroundColor:'#e53935',padding:13,borderRadius:10,alignItems:'center',marginTop:6},bt:{color:'#fff',fontWeight:'800'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd',padding:11,borderRadius:10,marginVertical:5},checkout:{backgroundColor:'#fff',padding:12,borderRadius:14},card:{backgroundColor:'#fff',padding:11,borderRadius:12,marginBottom:7},status:{color:'#e53935',fontWeight:'800'},link:{color:'#e53935',fontWeight:'700'},support:{backgroundColor:'#17202a',padding:14,borderRadius:14,alignItems:'center',marginTop:8},message:{backgroundColor:'#fff',padding:11,borderRadius:12,marginVertical:5}});
